# Generated by Django 5.0.6 on 2024-06-22 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_t_donor_td_description_t_donor_td_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_donor',
            name='td_howtocontact',
        ),
    ]
