# Generated by Django 5.0.6 on 2024-06-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_t_donor_td_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
